repos:

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/mundialis/github-workflows
    rev: 7dfc974164eac2aecb4fd7f76346519ec4f50d55
    hooks:
    -   id: linting
