name: Black code style check

on: [push]

jobs:
  black:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3 python3-pip
    - name: Add the bin directory pip uses for executables on PATH
      run: |
        echo "::add-path::/home/runner/.local/bin"
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install black
        black --version
    - name: Check code style with Black
      run: |
        black --check --diff --line-length 79 .
